version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: perfectpay-laravel
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./code:/var/www/html
    networks:
      - perfectpay_network

  servidor:
    image: nginx:alpine
    container_name: perfectpay-nginx
    restart: unless-stopped
    depends_on:
      - laravel
    ports:
      - "8001:80"
    volumes:
      - ./code/:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - perfectpay_network

networks:
  perfectpay_network:
    driver: bridge